apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tic-tac
  template:
    metadata:
      labels:
        app: tic-tac
    spec:
      containers:
        - name: tic-tac-container
          image: 10.100.102.175:8082/docker-local/tic-tac-toe:IMAGE_TAG_TO_REPLACE
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tic-tac-svc
spec:
  type: NodePort
  selector:
    app: tic-tac
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
